### ISSUE TITLE
RT - missing 2nd level menu of programs with new update

### ISSUE THREAD

**Issue by internetshortwave** [learningit/plugin.video.rt#1]
The recent update for RT seems to have erased the second set of menus for the various shows, Worlds Apart, In the Now, Keiser Report, etc. 

Now only has the live feeds.

**Comment by learningit** [comment]
Please use the forum link on kodi.org for support given in addon.xml. You need to post a log, pointless putting here in github.

**Comment by internetshortwave** [comment]
Will do - thanks
